### create a new patient entity
POST http://localhost:8080/api/v1/auth/register/super-admin
Content-Type: application/json

{
  "name":"Sandaru Gunathilake",
  "mobile": "0701794934",
  "email": "maduhansadilshan@gmail.com",
  "username": "maduhansadilshan@gmail.com",
  "password": "Dilshan2000@",
  "userType": "SUPER_ADMIN"
}

###